apiVersion: v1
kind: Secret
metadata:
  name: sports-secrets
type: Opaque
stringData:
  # 여기에 본인 키를 직접 붙여넣으세요 (따옴표 없이)
  DB_ACCESS_KEY_ID: AKIATACHV3WMUMKILEF3
  DB_SECRET_ACCESS_KEY: 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
  DB_REGION: ap-northeast-2