apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-website
spec:
  replicas: 3 # 서버 3개 띄우기
  selector:
    matchLabels:
      app: sports-web
  template:
    metadata:
      labels:
        app: sports-web
    spec:
      containers:
      - name: website
        image: website-img:latest
        imagePullPolicy: Never # 로컬 이미지 사용
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: sports-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: sports-web-service
spec:
  type: LoadBalancer # 내 컴퓨터(Localhost)로 연결
  selector:
    app: sports-web
  ports:
    - protocol: TCP
      port: 80       # 브라우저에선 80번(기본)으로 접속
      targetPort: 3000 # 컨테이너의 3000번으로 연결